//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IAsyncService")]
    public interface IAsyncService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsyncService/Fun1")]
        void Fun1(string s);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsyncService/Fun1")]
        System.Threading.Tasks.Task Fun1Async(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncService/Fun2", ReplyAction="http://tempuri.org/IAsyncService/Fun2Response")]
        void Fun2(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncService/Fun2", ReplyAction="http://tempuri.org/IAsyncService/Fun2Response")]
        System.Threading.Tasks.Task Fun2Async(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsyncServiceChannel : Client.ServiceReference3.IAsyncService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsyncServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference3.IAsyncService>, Client.ServiceReference3.IAsyncService {
        
        public AsyncServiceClient() {
        }
        
        public AsyncServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Fun1(string s) {
            base.Channel.Fun1(s);
        }
        
        public System.Threading.Tasks.Task Fun1Async(string s) {
            return base.Channel.Fun1Async(s);
        }
        
        public void Fun2(string s) {
            base.Channel.Fun2(s);
        }
        
        public System.Threading.Tasks.Task Fun2Async(string s) {
            return base.Channel.Fun2Async(s);
        }
    }
}
