//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference5 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Contract")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double feeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isBorrowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fee {
            get {
                return this.feeField;
            }
            set {
                if ((this.feeField.Equals(value) != true)) {
                    this.feeField = value;
                    this.RaisePropertyChanged("fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isBorrowed {
            get {
                return this.isBorrowedField;
            }
            set {
                if ((this.isBorrowedField.Equals(value) != true)) {
                    this.isBorrowedField = value;
                    this.RaisePropertyChanged("isBorrowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.Library", CallbackContract=typeof(Client.ServiceReference5.LibraryCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface Library {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Library/borrow", ReplyAction="http://tempuri.org/Library/borrowResponse")]
        void borrow(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Library/borrow", ReplyAction="http://tempuri.org/Library/borrowResponse")]
        System.Threading.Tasks.Task borrowAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Library/add", ReplyAction="http://tempuri.org/Library/addResponse")]
        void add(Client.ServiceReference5.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Library/add", ReplyAction="http://tempuri.org/Library/addResponse")]
        System.Threading.Tasks.Task addAsync(Client.ServiceReference5.Book book);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Library/findByTitle")]
        void findByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Library/findByTitle")]
        System.Threading.Tasks.Task findByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Library/getTitleById", ReplyAction="http://tempuri.org/Library/getTitleByIdResponse")]
        string getTitleById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Library/getTitleById", ReplyAction="http://tempuri.org/Library/getTitleByIdResponse")]
        System.Threading.Tasks.Task<string> getTitleByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Library/getAllBooks")]
        void getAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Library/getAllBooks")]
        System.Threading.Tasks.Task getAllBooksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LibraryCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Library/handleFindByTitle")]
        void handleFindByTitle(Client.ServiceReference5.Book[] books);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LibraryChannel : Client.ServiceReference5.Library, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryClient : System.ServiceModel.DuplexClientBase<Client.ServiceReference5.Library>, Client.ServiceReference5.Library {
        
        public LibraryClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LibraryClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LibraryClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void borrow(int id) {
            base.Channel.borrow(id);
        }
        
        public System.Threading.Tasks.Task borrowAsync(int id) {
            return base.Channel.borrowAsync(id);
        }
        
        public void add(Client.ServiceReference5.Book book) {
            base.Channel.add(book);
        }
        
        public System.Threading.Tasks.Task addAsync(Client.ServiceReference5.Book book) {
            return base.Channel.addAsync(book);
        }
        
        public void findByTitle(string title) {
            base.Channel.findByTitle(title);
        }
        
        public System.Threading.Tasks.Task findByTitleAsync(string title) {
            return base.Channel.findByTitleAsync(title);
        }
        
        public string getTitleById(int id) {
            return base.Channel.getTitleById(id);
        }
        
        public System.Threading.Tasks.Task<string> getTitleByIdAsync(int id) {
            return base.Channel.getTitleByIdAsync(id);
        }
        
        public void getAllBooks() {
            base.Channel.getAllBooks();
        }
        
        public System.Threading.Tasks.Task getAllBooksAsync() {
            return base.Channel.getAllBooksAsync();
        }
    }
}
